### ISSUE TITLE
concourse bosh commands logs are not as precise as same command on bosh cli

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1026]
### Expected behavior

* As a paas-templates operator 
* In order to 
  - benefits from all improvements on the bosh CLI in CI/CD concourse logs
* I need 
  - a more recent version of bosh CLI used on COA concourse pipelines

### Observed behavior

examples1 : pre/post start/stop indications in bosh deploy logs

example 2: precise indication of the failed ops file when having interpolation issue

```
[root@localhost operators]# ./interpolate.sh 
Error 'operation [0] in ./40-shieldv8-add-shield-import-members-errand-operators.yml failed': Expected to find exactly one matching array item for path '/instance_groups/name=shield/jobs/name=import' but found 0
```
in concourse
```
 Expected to find exactly one matching array item for path '/instance_groups/name=shield/jobs/name=import' but found 0 
```

=> no indication of the precise failing ops file

 
### Affected releases

* paas-templates 49.x
* COA 5.0.3
* bosh cli version 6.2.0-e5ce64ab-2020-01-16T19:22:05Z

**Comment by o-orand** [comment]
This should be solved by https://github.com/orange-cloudfoundry/cf-ops-automation/pull/337

**Comment by poblin-orange** [comment]
ko with 50.0.0, no pre-stop/pre-start info in concourse logs

**Comment by gberche-orange** [comment]
Still missing logs for bosh operations triggered by bosh deployment concourse resource
* [ ] check whether bosh deployment concourse resource produce more logs
* [ ] bump bosh deployment concourse resource ?

**Comment by o-orand** [comment]
No evolution on https://github.com/cloudfoundry/bosh-deployment-resource since march 2020, so latest bosh cli evolution are not available 😞
